/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

import java.io.IOException;
import java.sql.SQLOutput;
import java.sql.Time;
import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("Train Booking System");
        Scanner sc = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;
        try{
            userBookingService = new UserBookingService();
        }catch(IOException ex){
            ex.printStackTrace();
            return;
        }
        while(option != 7){
            System.out.println("Choose Option");
            System.out.println("1. Sign Up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel My Booking");
            System.out.println("7. Exit the Application");
            option = sc.nextInt();
            switch (option){
                case 1 :
                    System.out.println("Enter the Username to SignUp");
                    String nameToSignUp = sc.next();
                    System.out.println("Enter the password to SignUp");
                    String passwordToSignUp = sc.next();
                    User userToSignUp = new User(nameToSignUp, passwordToSignUp,
                                                UserServiceUtil.hashPassword(passwordToSignUp
                                                ), new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignUp);
                    break;
                case 2 :
                    System.out.println("Enter the username to Login");
                    String nameToLogin = sc.next();
                    System.out.println("Enter the password to SignIn");
                    String passwordToLogin = sc.next();
                    User userToLogin = new User(nameToLogin, passwordToLogin,
                                                UserServiceUtil.hashPassword(passwordToLogin),
                                                new ArrayList<>(), UUID.randomUUID().toString());
                    try{
                        userBookingService = new UserBookingService(userToLogin);
                    }catch(IOException ex){
                        return;
                    }
                    break;
                case 3 :
                    System.out.println("Fetching your Bookings.");
                    userBookingService.fetchBooking();
                    break;
                case 4 :
                    System.out.println("Type your source Station");
                    String source = sc.next();
                    System.out.println("Type your Destination Station");
                    String destination = sc.next();
                    List<Train> trains = userBookingService.getTrains(source, destination);
                    int index = 1;
                    for(Train t : trains){
                        System.out.println(index + " Train id : "+ t.getTrainId());
                        for(Map.Entry<String, Time> entry : t.getStationTimes().entrySet()){
                            System.out.println("Station " + entry.getKey()+ " time: "+ entry.getValue());
                        }
                    }
                    System.out.println("Select a train by typing 1,2,3...");
                case 5:
                    System.out.println("Enter the preference of the seat that you want(like window or something...)");

            }
        }
    }
}
